config/routes.rb
Visdir::Application.routes.draw do

  root :to => 'pages#index'
  
  resources :users
  resources :listings
  resources :categories
  
  get "/logout" => 'logins#destroy', :as => "logout"
  
  get "/login" => 'logins#new', :as => "login"
  post "/login" => 'logins#create', :as => "create_login"
  
  post "/create_user" => 'users#create', :as => "create_user"
  get "/signup" => 'users#new', :as => "signup"
  
  get "/favs" => 'pages#favs'
  
  get "/about" => 'pages#about'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :listings
  
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :budget_type, :category_id, :location, :name, :user_id, :photo, :categories_attributes
  belongs_to :users
  belongs_to :categories
  
  accepts_nested_attributes_for :categories, :allow_destroy => true, :reject_if => :category_is_blank
  
  def category_is_blank(attrs)
    if attrs['name'].blank?
      true
    else
      false
    end 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :twitter, :pro, :password_digest, :password, :password_confirmation
  has_many :listings
  
  has_secure_password
  validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  
  def authorize
    if current_user.nil?
      redirect_to login_path, :alert => "You need to log in to do that."
    end
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController  
  
  def index
    @categories = Category.all
  end

  def show
    @category=Category.find(params[:id])
  end

  def new
    @category=Category.new
  end

  def create
    @category=Category.new(params[:category])

    if @category.save
      u=User.find(session[:user_id])
      u.categories << @category
      redirect_to categories_path
    else
      render "new"
    end
  end

  def edit
    @category=Category.find(params[:id])
  end

  def update
    @category=Category.find(params[:id])

    if @category.update_attributes(params[:category])
      redirect_to category_path(@category.id)
    else
      render "edit"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    redirect_to categories_path
  end
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  def index
    @listings = Listing.all
    # @current_user_listings = current_user.listings
  end

  def show
    @listing=Listing.find(params[:id])
  end

  def new
    @listing=Listing.new
  end

  def create
    @listing=Listing.new(params[:listing])

    if @listing.save
      u=User.find(session[:user_id])
      u.listings << @listing
      redirect_to listings_path
    else
      render "new"
    end
  end

  def edit
    @listing=Listing.find(params[:id])
  end

  def update
    @listing=Listing.find(params[:id])

    if @listing.update_attributes(params[:listing])
      redirect_to listing_path(@listing.id)
    else
      render "edit"
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    redirect_to listings_path
  end
  
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_filter :authorize, :only => [:new, :create]
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path, notice: "Invalid Login"
    end
  end
  
  def destroy
    session[:user_id] = nil # Could also call `reset_session` to clear the entire session.
    redirect_to root_path
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def index
     # @current_user=User.find(session[:user_id])
     # @prolisting = Listing.find(params[:id])
     # @listings = Listing.all
    end

    def favs
      @user = session[:user_id]
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end

  def show
    @user=User.find(params[:id])
  end

  def new
    @user=User.new
  end

  def create
    @user=User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "new"
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to user_path(@user.id)
    else
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to listings_path
  end  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Visdir - <%= @current_user %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= session %>

<%= yield %>

</body>
</html>

app/views/listings/index.html.erb
<h1>Listings:</h1>

<ul>
  <% @listings.each do |listing| %>
    <%= content_tag_for :li, listing do %>
      
      <%= listing.name %>
      
      <%= listing.location %>
      
      <%= listing.budget_type %>
      
      <%= listing.photo %>
      
      <%= listing.user_id %>
      
      <%= listing.category_id %>
      
      <% end %>
   
    <% end %>
</ul>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= form_for @listing do |f| %>

  <div class='field'>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class='field'>
    <%= f.label :budget_type %><br />
    <%= f.text_field :budget_type %>
  </div>

  <div class='field'>
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>

  <%= f.fields_for :category do |a| %>

    <div class='field'>
      <%= a.label 'Category' %><br />
      <%= a.text_field :name %>
    </div>

    <% end %>
    
 <div class='field'>
   <%= f.label 'Upload a sample of your work' %><br />
   <%= f.text_field :photo %>
 </div>
 
 <div class='field'>
    <%= f.hidden_field :user_id, :value => session[:user_id] %>
 </div>
  
  

  

<% end %>

app/views/logins/new.html.erb
<div id="login_form">
<%= form_tag create_login_path do %>
  <p>
  <%= label_tag :email %><br />
  <%= text_field_tag :email, params[:email] %>
  </p>

  <p>
  <%= label_tag :password %><br />
  <%= password_field_tag :password, params[:password] %>
  </p>

  <%= submit_tag "Login", :id => "submit" %>
<% end %>
</div>

<p id="n_user">Are you a new user?</p>
<%=link_to("Create a new account", signup_path) %>

app/views/pages/about.html.erb
<h1>About VisDir</h1>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisDir</title> 
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Roboto+Slab:700,400' type='text/css'>
  <link rel="stylesheet" href="css/application.css" type='text/css'>
  <script type="text/javascript" src="scripts/application.js"></script>
</head>
<body>

<header>
  <div id="header">
    <h1 id="header-logo"><%= link_to "VisDir", root_path%></h1>
  
    <nav id="header-nav">
      <ul id="header-nav-ul">
        <li><a href="/favs" class="header-nav-link">Favs</a></li>
        <li><a href="/about" class="header-nav-link">About</a></li>
      </ul>
    </nav>
  
    <div id="header-account">
      <div id="header-account-label">Photographers</div>
    
      <ul id="header-account-ul">
  	    <% if current_user %>
  	      <%= current_user.email %> <%= link_to "Log Out", logout_path %>
  	    <% else %>
          <li id="header-account-login"><a href="/login">Log in</a> or</li>
          <li id="header-account-signup"><a href="/signup">Sign up</a></li>
  	    <% end %>
      </ul>
    </div>
  </div>
</header>

<main>
  <div id="main">
    <div id="searchbar">
      <div id="searchbar-label">I'm looking for</div>
    
      <div class="searchbar-section">
        <select>
          <option>All</option>
          <option>Senior Portrait</option>
          <option>Wedding</option>
          <option>Real Estate</option>
        </select>
      
        <div class="searchbar-section-label">Photographers</div>
      </div>
    
      <div class="searchbar-label_section">in</div>
    
      <div class="searchbar-section">
        <select>
          <option>All Locations</option>
          <option>Washington, D.C.</option>
          <option>Omaha, NE</option>
          <option>Council Bluffs, NE</option>
        </select>
      </div>
    
      <div class="searchbar-label_section">for</div>
    
      <div class="searchbar-section">
        <select>
          <option>Any Budget</option>
          <option>Low Budget</option>
          <option>High Budget</option>
        </select>
      </div>
    </div>
  
    <div id="cards">
      <div class="card card-pro">
        <a href="#" class="card-fav">Add to Favs</a>
      
        <div class="card-preview">
          <a href="/listing/1"><img src="http://placekitten.com/g/200/180"></a>
        </div>
      
        <h2 class="card-header"><a href="/listing/1">ACME Photography</a></h2>
      
        <div class="card-details">
          <div class="card-details-location">Omaha, NE</div>
          <div class="card-details-budget">Low Budget</div>
        </div>
      </div>
    
      <div class="card card-pro">
        <a href="#" class="card-fav">Remove from Favs</a>
      
        <div class="card-preview">
          <a href="/listing/90"><img src="http://placekitten.com/g/200/180"></a>
        </div>
      
        <h2 class="card-header"><a href="/listing/90">Tiny Lens Studios</a></h2>
      
        <div class="card-details">
          <div class="card-details-location">Lincoln, NE</div>
          <div class="card-details-budget">High Budget</div>
        </div>
      </div>
    
      <div class="card">
        <a href="#" class="card-fav">Remove from Favs</a>
        
        <h2 class="card-header"><a href="/listing/11">Still Photography</a></h2>
      
        <div class="card-preview">
          <a href="/listing/11"><img src="http://placekitten.com/g/200/180"></a>
        </div>
      
        <div class="card-details">
          <div class="card-details-location">Omaha, NE</div>
          <div class="card-details-budget">High Budget</div>
        </div>
      </div>
    
      <div class="card">
        <a href="#" class="card-fav">Add to Favs</a>
        
        <h2 class="card-header"><a href="/listing/21">Ansel Adams</a></h2>
      
        <div class="card-preview">
          <a href="/listing/21"><img src="http://placekitten.com/g/200/180"></a>
        </div>
      
        <div class="card-details">
          <div class="card-details-location">Omaha, NE</div>
          <div class="card-details-budget">High Budget</div>
        </div>
      </div>
    
      <div class="card">
        <a href="#" class="card-fav">Add to Favs</a>
        
        <h2 class="card-header"><a href="/listing/54">Instagram Studios</a></h2>
      
        <div class="card-preview">
          <a href="/listing/54"><img src="http://placekitten.com/g/200/180"></a>
        </div>
      
        <div class="card-details">
          <div class="card-details-location">Lincoln, NE</div>
          <div class="card-details-budget">Low Budget</div>
        </div>
      </div>
    </div>
  </div>
</main>

<footer>
  <div id="footer">
    <a href="#">VisDir</a>
  </div>
</footer>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if @user.errors %>
  <% @user.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

<%= form_for @user, :url => create_user_path do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  
  <%= f.submit %>

<% end %>